GET http://127.0.0.1:3000/cocktails
###
GET http://127.0.0.1:3000/cocktails/Rob Roy/zutaten
###
GET http://127.0.0.1:3000/cocktails/6.5

###
DELETE http://127.0.0.1:3000/cocktails/Adonis
###
POST http://127.0.0.1:3000/cocktails
Content-Type: application/json

{
    "cname": "Apfel Tasche",
    "preis": 0.50,
    "zubereitung": "Apfelmuss",
    "kid": 5,
    "zgid": 5,
    "sgid": 5
}
###

PATCH http://127.0.0.1:3000/cocktails/Rob Roy
Content-Type: application/json

{
    "preis": 0.1
}